spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Bodegon
    username: postgres
    password: Agusagusbmx15$
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
